project:
  output-dir: docs

website:
  navbar:
    left:
      - href: index.qmd
        text: Start
      - href: Erste_Erkenntnisse.qmd
        text: Erste Erkenntnisse
      - href: verkehrsdebatte_themen.html
        text: Debatten-Themen

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



